### ISSUE TITLE
运行demo base缺少依赖

### ISSUE THREAD

**Issue by darkgirl** [richard1015/nutui-demo#1]
我的nodejs是14的
 ERROR  Failed to compile with 1 errors                                                                      下午2:18:25
This dependency was not found:

* @nutui/nutui/dist/packages/qart/qart.js in ./src/main.js

To install it, you can run: npm install --save @nutui/nutui/dist/packages/qart/qart.js
终止批处理操作吗(Y/N)? y

E:\javascript\nutui-demo\base>npm install --save @nutui/nutui/dist/packages/qart/qart.js
npm ERR! code ENOLOCAL
npm ERR! Could not install from "@nutui\nutui\dist\packages\qart\qart.js" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\veilblade\AppData\Roaming\npm-cache\_logs\2020-05-04T06_18_47_925Z-debug.log

E:\javascript\nutui-demo\base>cnpm install --save @nutui/nutui/dist/packages/qart/qart.js
× Install fail! Error: [@@nutui/nutui/dist/packages/qart/qart.js] resolved target E:\javascript\nutui-demo\base\@nutui\nutui\dist\packages\qart\qart.js error: ENOENT: no such file or directory, lstat 'E:\javascript\nutui-demo\base\@nutui'
Error: [@@nutui/nutui/dist/packages/qart/qart.js] resolved target E:\javascript\nutui-demo\base\@nutui\nutui\dist\packages\qart\qart.js error: ENOENT: no such file or directory, lstat 'E:\javascript\nutui-demo\base\@nutui'
    at module.exports (C:\Users\veilblade\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\download\local.js:30:11)
    at module.exports.throw (<anonymous>)
    at onRejected (C:\Users\veilblade\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:81:24)
npminstall version: 3.27.0
npminstall args: D:\software\nodejs14\node.exe C:\Users\veilblade\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --fix-bug-versions --china --userconfig=C:\Users\veilblade\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://r.npm.taobao.org --save @nutui/nutui/dist/packages/qart/qart.js

E:\javascript\nutui-demo\base>

用npm或者cnpm都不能安装qart.js

**Comment by richard1015** [comment]
已修复，感谢您的反馈
